Сheck simplier ver

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -19,11 +19,11 @@ jobs:
       - name: Build and Run Docker Compose
         run: |
           if docker-compose exec web poetry run pytest --maxfail=1 --disable-warnings -q; then
-                echo "Tests passed."
-              else
-                echo "Tests failed."
-                exit 1
-              fi
+            echo "Tests passed."
+          else
+            echo "Tests failed."
+            exit 1
+          fi
 
       - name: Run tests inside Docker container
         run: docker-compose exec web poetry run pytest --maxfail=1 --disable-warnings -q
