test

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -6,6 +6,8 @@ on:
       - be_19_add_aws_structure
 
 jobs:
+  env:
+    BRANCH_NAME: be_19_add_aws_structure
   setup-and-test:
     runs-on: ubuntu-latest
 
@@ -23,8 +25,8 @@ jobs:
 
               echo "Switching to the correct branch..."
               git fetch origin
-              git checkout be_19_add_aws_structure
-              git pull origin be_19_add_aws_structure
+              git checkout $BRANCH_NAME
+              git pull origin $BRANCH_NAME
 
               echo "Stopping and removing existing containers..."
               docker-compose down || true
@@ -32,8 +34,12 @@ jobs:
               echo "Building and running Docker Compose with the latest images..."
               docker-compose up -d --build
 
-              echo "Running tests..."
-              docker-compose exec web poetry run pytest --maxfail=1 --disable-warnings -q || exit 1
+              if docker-compose exec web poetry run pytest --maxfail=1 --disable-warnings -q; then
+                echo "Tests passed."
+              else
+                echo "Tests failed."
+                exit 1
+              fi
           
               echo "Stopping test environment..."
               docker-compose down || true
@@ -57,8 +63,8 @@ jobs:
 
               echo "Pulling latest code from git repository..."
               git fetch origin
-              git checkout be_19_add_aws_structure
-              git pull origin be_19_add_aws_structure
+              git checkout $BRANCH_NAME
+              git pull origin $BRANCH_NAME
 
               echo "Stopping and removing existing containers..."
               docker-compose down || true
